{
 "title": "Runiq (Worker Pool)",
 "panels": [
  {
   "title": "Fila Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(runiq_jobs_count{queue=\"votes_queue\", status=\"pending\"})",
     "legendFormat": "Pending Jobs"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(runiq_jobs_count{queue=\"votes_queue\", status=\"running\"})",
     "legendFormat": "Active (Running)"
    }
   ]
  },
  {
   "title": "Dead Jobs / Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(runiq_jobs_count{queue=\"votes_queue\", status=\"failed\"})",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  {
   "title": "Processed Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max(runiq_jobs_count{queue=\"votes_queue\", status=\"processed\"})",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Worker Throughput (Jobs/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(rate(runiq_jobs_count{queue=\"votes_queue\", status=\"processed\"}[1m]))",
     "legendFormat": "Jobs/sec"
    }
   ]
  }
 ]
}