global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ingestion_worker'
    static_configs:
      - targets: ['ingestion-worker:8081']

  - job_name: 'ingestion_api'
    static_configs:
      - targets: ['ingestion-api:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
