apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Apenas pods com o label app = ingestion-api ou ingestion-worker
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: (ingestion-api|ingestion-worker)
          
          # Manter apenas pods no estado 'Running'
          - source_labels: [__meta_kubernetes_pod_phase]
            action: keep
            regex: Running
          
          # Renomear o label do job para o nome do app (ingestion-api ou ingestion-worker)
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: job
          
          # Salvar o nome do pod
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
            
          # O Prometheus descobrirá automaticamente as portas dos containers,
          # mas podemos forçar mapeando as anotações ou sabendo as portas.
          # Como sabemos que API roda na 8080 e Worker na 8081:
          - source_labels: [__meta_kubernetes_pod_label_app, __address__]
            action: replace
            regex: ingestion-api;([^:]+)(?::\d+)?
            replacement: $1:8080
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app, __address__]
            action: replace
            regex: ingestion-worker;([^:]+)(?::\d+)?
            replacement: $1:8081
            target_label: __address__
